/* Image credits (generated by tools/fetch_images.py). */
self.OTZ_CREDITS = [
 {
  "id": "angelina",
  "file": "AngelinaParis.JPG",
  "title": "Angelina (salon de thé)",
  "artist": "Robert Schediwy",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:AngelinaParis.JPG"
 },
 {
  "id": "arrival",
  "file": "Rue Montorgueil - Paris II (FR75) - 2024-12-07 - 1.jpg",
  "title": "Rue Montorgueil night",
  "artist": "Chabe01",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Rue_Montorgueil_-_Paris_II_(FR75)_-_2024-12-07_-_1.jpg"
 },
 {
  "id": "avengers",
  "file": "Thor et Loky, Marvel Avengers Campus, Disney Adventure World, Disneyland Paris.jpg",
  "title": "Avengers Campus Disneyland Paris",
  "artist": "Florent Abel",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Thor_et_Loky,_Marvel_Avengers_Campus,_Disney_Adventure_World,_Disneyland_Paris.jpg"
 },
 {
  "id": "bateau-lavoir",
  "file": "Bateau-Lavoir_face_avant.jpg",
  "title": "Bateau-Lavoir",
  "artist": "Kalashni",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Bateau-Lavoir_face_avant.jpg"
 },
 {
  "id": "berthillon",
  "file": "Le_quai_de_Béthune_dans_l'île_St_Louis,_le_pont_de_la_Tournelle_et_la_Seine.jpg",
  "title": "Île Saint-Louis",
  "artist": "Jean-Pierre Dalbéra",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Le_quai_de_B%C3%A9thune_dans_l%27%C3%AEle_St_Louis,_le_pont_de_la_Tournelle_et_la_Seine.jpg"
 },
 {
  "id": "big-thunder",
  "file": "Parc Disneyland - Chessy (FR77) - 2025-10-13 - 10.jpg",
  "title": "Disneyland Paris",
  "artist": "Chabe01",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Parc_Disneyland_-_Chessy_(FR77)_-_2025-10-13_-_10.jpg"
 },
 {
  "id": "boat",
  "file": "Millenium_bridge_2015.jpg",
  "title": "Millennium Bridge, London",
  "artist": "Ibex73",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Millenium_bridge_2015.jpg"
 },
 {
  "id": "borough",
  "file": "London_2018_March_IMG_0663.jpg",
  "title": "Borough Market",
  "artist": "Øyvind Holmstad",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:London_2018_March_IMG_0663.jpg"
 },
 {
  "id": "brick-lane",
  "file": "Brick_Lane_Mosque2.JPG",
  "title": "Brick Lane Mosque",
  "artist": "Lemur12",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Brick_Lane_Mosque2.JPG"
 },
 {
  "id": "british-museum",
  "file": "Rosetta_Stone.JPG",
  "title": "Rosetta Stone",
  "artist": "Hans Hillewaert",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Rosetta_Stone.JPG"
 },
 {
  "id": "bus15",
  "file": "St_Pauls_aerial_(cropped).jpg",
  "title": "St Paul's Cathedral",
  "artist": "Mark Fosh",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:St_Pauls_aerial_(cropped).jpg"
 },
 {
  "id": "camden",
  "file": "Camden_markets_entrance.JPG",
  "title": "Camden Market",
  "artist": "en:User:Grim23",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Camden_markets_entrance.JPG"
 },
 {
  "id": "carnaby",
  "file": "Carnaby street sign on Regent Street.jpg",
  "title": "Carnaby Street",
  "artist": "VirtuallyLondonBecky",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Carnaby_street_sign_on_Regent_Street.jpg"
 },
 {
  "id": "cassis",
  "file": "Paul_Signac_-_Cassis,_Cap_Lombard,_Opus_196_-_Google_Art_Project.jpg",
  "title": "Cassis, Cap Lombard, Opus 196",
  "artist": "Paul Signac",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:Paul_Signac_-_Cassis,_Cap_Lombard,_Opus_196_-_Google_Art_Project.jpg"
 },
 {
  "id": "castle",
  "file": "Parc Disneyland - Chessy (FR77) - 2025-10-13 - 26.jpg",
  "title": "Disneyland Paris",
  "artist": "Chabe01",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Parc_Disneyland_-_Chessy_(FR77)_-_2025-10-13_-_26.jpg"
 },
 {
  "id": "chinatown",
  "file": "London,_China_Town_--_2016_--_4868.jpg",
  "title": "Chinatown, London",
  "artist": "Dietmar Rabich",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:London,_China_Town_--_2016_--_4868.jpg"
 },
 {
  "id": "cite",
  "file": "The_western_sides_of_the_Île_de_la_Cité_and_the_Pont_Neuf,_14_July_2008.jpg",
  "title": "Pont Neuf",
  "artist": "Rmrfstar",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:The_western_sides_of_the_%C3%8Ele_de_la_Cit%C3%A9_and_the_Pont_Neuf,_14_July_2008.jpg"
 },
 {
  "id": "cruise",
  "file": "Pont_Alexandre_III_depuis_pont_de_la_Concorde_Paris.jpg",
  "title": "Pont Alexandre III",
  "artist": "Jebulon",
  "license": "CC0",
  "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
  "page": "https://commons.wikimedia.org/wiki/File:Pont_Alexandre_III_depuis_pont_de_la_Concorde_Paris.jpg"
 },
 {
  "id": "crush",
  "file": "Crush’s Coaster, Worlds of Pixar, Disney Adventure World, Disneyland Paris.jpg",
  "title": "Crush's Coaster",
  "artist": "Florent Pécassou",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Crush%E2%80%99s_Coaster,_Worlds_of_Pixar,_Disney_Adventure_World,_Disneyland_Paris.jpg"
 },
 {
  "id": "deux-moulins",
  "file": "Paris - Café des 2 Moulins - 2004.jpg",
  "title": "Café des Deux Moulins Montmartre",
  "artist": "France74",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
  "page": "https://commons.wikimedia.org/wiki/File:Paris_-_Caf%C3%A9_des_2_Moulins_-_2004.jpg"
 },
 {
  "id": "eden",
  "file": "Eden_Théâtre_(La_Ciotat).jpeg",
  "title": "L'Eden Théâtre",
  "artist": "Un Fou",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Eden_Th%C3%A9%C3%A2tre_(La_Ciotat).jpeg"
 },
 {
  "id": "eiffel",
  "file": "Reflet-tour-Eiffel-Paris-Luc-Viatour.jpg",
  "title": "Eiffel Tower from below",
  "artist": "Lviatour",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Reflet-tour-Eiffel-Paris-Luc-Viatour.jpg"
 },
 {
  "id": "enfants-rouges",
  "file": "Marché_des_Enfants-Rouges,_Paris_July_2014.jpg",
  "title": "Marché des Enfants Rouges",
  "artist": "Connie Ma from Chicago, United States of America",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:March%C3%A9_des_Enfants-Rouges,_Paris_July_2014.jpg"
 },
 {
  "id": "eurostar",
  "file": "TGV_TMST_3011-2_-_Sortie_Tunnel_sous_la_Manche_à_Coquelles.jpg",
  "title": "Channel Tunnel",
  "artist": "Billy69150 (voir les conditions d'utilisation / see licensing below)",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:TGV_TMST_3011-2_-_Sortie_Tunnel_sous_la_Manche_%C3%A0_Coquelles.jpg"
 },
 {
  "id": "eurostar-back",
  "file": "Croisement_Thalys-Eurostar_Neige_en_Savoie_(février_2023).JPG",
  "title": "Eurostar",
  "artist": "Florian Pépellin",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Croisement_Thalys-Eurostar_Neige_en_Savoie_(f%C3%A9vrier_2023).JPG"
 },
 {
  "id": "fitzrovia",
  "file": "1350342_II_BT_COMMUNICATION_TOWER,_CLEVELAND_MEWS_Camden_London_20250612_0003.jpg",
  "title": "BT Tower",
  "artist": "Tilman2007",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:1350342_II_BT_COMMUNICATION_TOWER,_CLEVELAND_MEWS_Camden_London_20250612_0003.jpg"
 },
 {
  "id": "gare-la-ciotat",
  "file": "L'Arrivée d'un train en gare de La Ciotat.jpg",
  "title": "L'Arrivée d'un train en gare de La Ciotat.jpg",
  "artist": "w:Auguste and Louis Lumière (Louis d. 1948, Auguste d. 1954)",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:L%27Arriv%C3%A9e_d%27un_train_en_gare_de_La_Ciotat.jpg"
 },
 {
  "id": "guard",
  "file": "Buckingham_Palace_London_Morning_2020_01_(cropped).jpg",
  "title": "Buckingham Palace",
  "artist": "Julian Herzog (Website)",
  "license": "CC BY 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Buckingham_Palace_London_Morning_2020_01_(cropped).jpg"
 },
 {
  "id": "hall-d16",
  "file": "RueMontorgueil.JPG",
  "title": "Rue Montorgueil",
  "artist": "Minato ku",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:RueMontorgueil.JPG"
 },
 {
  "id": "hall-d17",
  "file": "Louvre_Museum_Wikimedia_Commons.jpg",
  "title": "Louvre",
  "artist": "Benh LIEU SONG (Flickr)",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Louvre_Museum_Wikimedia_Commons.jpg"
 },
 {
  "id": "hall-d18",
  "file": "Tour Eiffel Wikimedia Commons.jpg",
  "title": "Tour Eiffel Wikimedia Commons.jpg",
  "artist": "Benh LIEU SONG",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:Tour_Eiffel_Wikimedia_Commons.jpg"
 },
 {
  "id": "hall-d19",
  "file": "Le_sacre_coeur.jpg",
  "title": "Sacré-Cœur, Paris",
  "artist": "Tonchino",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Le_sacre_coeur.jpg"
 },
 {
  "id": "hall-d20",
  "file": "Neal's_Yard_20130408_034.jpg",
  "title": "Neal's Yard",
  "artist": "Elisa.rolle",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Neal%27s_Yard_20130408_034.jpg"
 },
 {
  "id": "hall-d21",
  "file": "Tower_Bridge_at_Dawn.jpg",
  "title": "Tower Bridge",
  "artist": "Fuzzypiggy",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Tower_Bridge_at_Dawn.jpg"
 },
 {
  "id": "hall-d22",
  "file": "British_Museum_from_NE_2.JPG",
  "title": "British Museum",
  "artist": "Ham",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
  "page": "https://commons.wikimedia.org/wiki/File:British_Museum_from_NE_2.JPG"
 },
 {
  "id": "hall-d23",
  "file": "Parc Disneyland - Chessy (FR77) - 2025-10-13 - 21.jpg",
  "title": "Disneyland Paris",
  "artist": "Chabe01",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Parc_Disneyland_-_Chessy_(FR77)_-_2025-10-13_-_21.jpg"
 },
 {
  "id": "hall-d24",
  "file": "Ratatouille (51414590388).jpg",
  "title": "Remy's Ratatouille Adventure",
  "artist": "elisfkc2",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Ratatouille_(51414590388).jpg"
 },
 {
  "id": "hall-d25",
  "file": "Façade_de_la_gare_de_Marseille-Saint-Charles-7689.jpg",
  "title": "Marseille-Saint-Charles station",
  "artist": "Raimond Spekking",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Fa%C3%A7ade_de_la_gare_de_Marseille-Saint-Charles-7689.jpg"
 },
 {
  "id": "hall-d26",
  "file": "La_Ciotat_-_Marina.jpg",
  "title": "La Ciotat",
  "artist": "Raffaele pagani",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:La_Ciotat_-_Marina.jpg"
 },
 {
  "id": "hall-d29",
  "file": "En-Vau_calanque_4.jpg",
  "title": "Calanques National Park",
  "artist": "kallerna",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:En-Vau_calanque_4.jpg"
 },
 {
  "id": "hamilton",
  "file": "Victoria_Palace_Theatre,_Victoria_(01).jpg",
  "title": "Victoria Palace Theatre",
  "artist": "Doyle of London",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Victoria_Palace_Theatre,_Victoria_(01).jpg"
 },
 {
  "id": "home",
  "file": "Marseille_Provence_Airport_2017_09.jpg",
  "title": "Marseille Provence Airport",
  "artist": "Georges Seguin (Okki)",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Marseille_Provence_Airport_2017_09.jpg"
 },
 {
  "id": "ile-verte",
  "file": "Ile_Verte_2.jpg",
  "title": "Île Verte (La Ciotat)",
  "artist": "davric",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:Ile_Verte_2.jpg"
 },
 {
  "id": "lafayette",
  "file": "Galerie Lafayette Haussmann Dome.jpg",
  "title": "Galeries Lafayette Haussmann",
  "artist": "Benh LIEU SONG (Flickr)",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Galerie_Lafayette_Haussmann_Dome.jpg"
 },
 {
  "id": "last-evening",
  "file": "Cap_Canaille_depuis_la_Gardiole.JPG",
  "title": "Cap Canaille",
  "artist": "B.Delpeuch",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Cap_Canaille_depuis_la_Gardiole.JPG"
 },
 {
  "id": "louvre",
  "file": "La_Liberté_guidant_le_peuple_-_Eugène_Delacroix_-_Musée_du_Louvre_Peintures_RF_129_-_après_restauration_2024.jpg",
  "title": "Liberty Leading the People",
  "artist": "Eugène Delacroix",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:La_Libert%C3%A9_guidant_le_peuple_-_Eug%C3%A8ne_Delacroix_-_Mus%C3%A9e_du_Louvre_Peintures_RF_129_-_apr%C3%A8s_restauration_2024.jpg"
 },
 {
  "id": "luxembourg",
  "file": "LuxembourgMontparnasse.JPG",
  "title": "Jardin du Luxembourg",
  "artist": "Kirua",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:LuxembourgMontparnasse.JPG"
 },
 {
  "id": "matilda",
  "file": "Cambridge_Theatre,_London,_28_July_2016_01.jpg",
  "title": "Cambridge Theatre",
  "artist": "Philafrenzy",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Cambridge_Theatre,_London,_28_July_2016_01.jpg"
 },
 {
  "id": "montorgueil",
  "file": "RueMontorgueil.JPG",
  "title": "Rue Montorgueil",
  "artist": "Minato ku",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:RueMontorgueil.JPG"
 },
 {
  "id": "mugel",
  "file": "Bec de l'Aigle 2.jpg",
  "title": "Bec de l'Aigle",
  "artist": "Alexander Freitas",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Bec_de_l%27Aigle_2.jpg"
 },
 {
  "id": "mur",
  "file": "Muro de los je t'aime, París, Francia, 2022-10-30, DD 01.jpg",
  "title": "Mur des je t'aime",
  "artist": "Diego Delso",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Muro_de_los_je_t%27aime,_Par%C3%ADs,_Francia,_2022-10-30,_DD_01.jpg"
 },
 {
  "id": "national-gallery",
  "file": "Vincent van Gogh - Wheat Field with Cypresses (National Gallery version).jpg",
  "title": "Wheatfield with Cypresses National Gallery London van Gogh",
  "artist": "Vincent van Gogh",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Wheat_Field_with_Cypresses_(National_Gallery_version).jpg"
 },
 {
  "id": "neals-yard",
  "file": "Neal's_Yard_20130408_034.jpg",
  "title": "Neal's Yard",
  "artist": "Elisa.rolle",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Neal%27s_Yard_20130408_034.jpg"
 },
 {
  "id": "nose",
  "file": "Paris Passage Grand-Cerf 2013.jpg",
  "title": "Passage du Grand-Cerf Paris",
  "artist": "JLPC",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Paris_Passage_Grand-Cerf_2013.jpg"
 },
 {
  "id": "notre-dame",
  "file": "Notre-Dame_de_Paris,_4_October_2017.jpg",
  "title": "Notre-Dame de Paris",
  "artist": "Ali Sabbagh",
  "license": "CC0",
  "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
  "page": "https://commons.wikimedia.org/wiki/File:Notre-Dame_de_Paris,_4_October_2017.jpg"
 },
 {
  "id": "ouigo",
  "file": "SNCF OUIGO TGV Dasye 761 Marseille - Paris.jpg",
  "title": "Ouigo",
  "artist": "Kabelleger / David Gubler",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:SNCF_OUIGO_TGV_Dasye_761_Marseille_-_Paris.jpg"
 },
 {
  "id": "palais-royal",
  "file": "Conseil_d'Etat_Paris_WA.jpg",
  "title": "Palais-Royal",
  "artist": "Marie-Lan Nguyen",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:Conseil_d%27Etat_Paris_WA.jpg"
 },
 {
  "id": "parade",
  "file": "Pinocchio_in_the_Disney_Stars_on_Parade,_Disneyland_Paris,_2026.jpg",
  "title": "Disney Stars on Parade",
  "artist": "DimiTalen",
  "license": "CC0",
  "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
  "page": "https://commons.wikimedia.org/wiki/File:Pinocchio_in_the_Disney_Stars_on_Parade,_Disneyland_Paris,_2026.jpg"
 },
 {
  "id": "passe-muraille",
  "file": "Le Passe-Muraille @ Montmartre @ Paris 18 (32146228024).jpg",
  "title": "Passe-muraille Marcel Aymé Montmartre",
  "artist": "Guilhem Vellut from Paris, France",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Le_Passe-Muraille_@_Montmartre_@_Paris_18_(32146228024).jpg"
 },
 {
  "id": "pavee",
  "file": "Paris-Marais-Synagoge-102-2017-gje.jpg",
  "title": "Agoudas Hakehilos Synagogue",
  "artist": "Gerd Eichmann",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Paris-Marais-Synagoge-102-2017-gje.jpg"
 },
 {
  "id": "petanque",
  "file": "Montlaux Joueurs de boules.jpg",
  "title": "pétanque boules Provence",
  "artist": "Unknown early 1900s",
  "license": "Public domain",
  "licenseUrl": "",
  "page": "https://commons.wikimedia.org/wiki/File:Montlaux_Joueurs_de_boules.jpg"
 },
 {
  "id": "peter-pan",
  "file": "Dlp_peter_pan.jpg",
  "title": "Peter Pan's Flight",
  "artist": "Carterhawk",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Dlp_peter_pan.jpg"
 },
 {
  "id": "piazza",
  "file": "Covent_Garden_Interior_May_2006_crop.jpg",
  "title": "Covent Garden",
  "artist": "Covent_Garden_Interior_May_2006.jpg: Diliff\nderivative work: SilkTork (talk)",
  "license": "CC BY 2.5",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
  "page": "https://commons.wikimedia.org/wiki/File:Covent_Garden_Interior_May_2006_crop.jpg"
 },
 {
  "id": "pirates",
  "file": "Pirates of the Caribbean Disneyland Paris.JPG",
  "title": "Pirates of the Caribbean Disneyland Paris",
  "artist": "Gian94g",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Pirates_of_the_Caribbean_Disneyland_Paris.JPG"
 },
 {
  "id": "platform",
  "file": "King's Cross Western Concourse.jpg",
  "title": "King's Cross station",
  "artist": "Colin",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:King%27s_Cross_Western_Concourse.jpg"
 },
 {
  "id": "postal",
  "file": "Mail_Rail_trains_(13267574833).jpg",
  "title": "London Post Office Railway",
  "artist": "Matt Brown from London, England",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Mail_Rail_trains_(13267574833).jpg"
 },
 {
  "id": "ratatouille",
  "file": "Ratatouille (51414590388).jpg",
  "title": "Remy's Ratatouille Adventure",
  "artist": "elisfkc2",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Ratatouille_(51414590388).jpg"
 },
 {
  "id": "rivoli59",
  "file": "Squat_à_Paris_(59,_rue_de_Rivoli,_1er_ardt).jpg",
  "title": "59 Rivoli",
  "artist": "Airair (talk · contribs)",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
  "page": "https://commons.wikimedia.org/wiki/File:Squat_%C3%A0_Paris_(59,_rue_de_Rivoli,_1er_ardt).jpg"
 },
 {
  "id": "rosiers",
  "file": "Rue_Rosiers_-_Paris_IV_(FR75)_-_2021-05-25_-_1.jpg",
  "title": "Rue des Rosiers",
  "artist": "Chabe01",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Rue_Rosiers_-_Paris_IV_(FR75)_-_2021-05-25_-_1.jpg"
 },
 {
  "id": "sacre-coeur",
  "file": "Le_sacre_coeur.jpg",
  "title": "Sacré-Cœur, Paris",
  "artist": "Tonchino",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Le_sacre_coeur.jpg"
 },
 {
  "id": "sainte-chapelle",
  "file": "Sainte_Chapelle_-_Upper_level_1.jpg",
  "title": "Sainte-Chapelle",
  "artist": "Didier B (Sam67fr)",
  "license": "CC BY-SA 2.5",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
  "page": "https://commons.wikimedia.org/wiki/File:Sainte_Chapelle_-_Upper_level_1.jpg"
 },
 {
  "id": "sens",
  "file": "Hôtel_de_Sens_1.jpg",
  "title": "Hôtel de Sens",
  "artist": "Camlamb",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:H%C3%B4tel_de_Sens_1.jpg"
 },
 {
  "id": "seven-dials",
  "file": "Seven_Dials_(Geograph-5808655-by-John-Sutton).jpg",
  "title": "Seven Dials, London",
  "artist": "John Sutton",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Seven_Dials_(Geograph-5808655-by-John-Sutton).jpg"
 },
 {
  "id": "shoreditch",
  "file": "View_from_Curtain_Road,_Shoreditch.jpg",
  "title": "Shoreditch",
  "artist": "DanielMichaelPerry",
  "license": "CC BY 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:View_from_Curtain_Road,_Shoreditch.jpg"
 },
 {
  "id": "southbank",
  "file": "London-Eye-2009.JPG",
  "title": "London Eye",
  "artist": "Khamtran",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:London-Eye-2009.JPG"
 },
 {
  "id": "st-charles",
  "file": "Façade_de_la_gare_de_Marseille-Saint-Charles-7689.jpg",
  "title": "Marseille-Saint-Charles station",
  "artist": "Raimond Spekking",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Fa%C3%A7ade_de_la_gare_de_Marseille-Saint-Charles-7689.jpg"
 },
 {
  "id": "st-pancras",
  "file": "St_Pancras_Railway_Station_2012-06-23.jpg",
  "title": "St Pancras railway station",
  "artist": "Colin",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:St_Pancras_Railway_Station_2012-06-23.jpg"
 },
 {
  "id": "tales",
  "file": "Disneyland Park 05, Paris 22 August 2013.jpg",
  "title": "Disneyland Park (Paris)",
  "artist": "flightlog",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Disneyland_Park_05,_Paris_22_August_2013.jpg"
 },
 {
  "id": "tertre",
  "file": "Restaurants,_Place_du_Tertre,_Paris_30_September_2019.jpg",
  "title": "Place du Tertre",
  "artist": "Pierre Blaché from Paris, France",
  "license": "CC0",
  "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
  "page": "https://commons.wikimedia.org/wiki/File:Restaurants,_Place_du_Tertre,_Paris_30_September_2019.jpg"
 },
 {
  "id": "totoro",
  "file": "New London Theatre, Drury Lane - geograph.org.uk - 3863620.jpg",
  "title": "New London Theatre Drury Lane",
  "artist": "Peter Trimming",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:New_London_Theatre,_Drury_Lane_-_geograph.org.uk_-_3863620.jpg"
 },
 {
  "id": "tower",
  "file": "Tower_of_London_from_the_Shard_(8515883950).jpg",
  "title": "Tower of London",
  "artist": "[Duncan] from Nottingham, UK",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Tower_of_London_from_the_Shard_(8515883950).jpg"
 },
 {
  "id": "tower-bridge",
  "file": "Tower_Bridge_at_Dawn.jpg",
  "title": "Tower Bridge",
  "artist": "Fuzzypiggy",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Tower_Bridge_at_Dawn.jpg"
 },
 {
  "id": "transport",
  "file": "London Transport Museum (42206944281).jpg",
  "title": "London Transport Museum",
  "artist": "Wei-Te Wong from Taipei City, Taiwan, Republic of China",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:London_Transport_Museum_(42206944281).jpg"
 },
 {
  "id": "tuileries",
  "file": "Crowd_in_the_Jardin_des_Tuileries,_Paris_July_2014.jpg",
  "title": "Tuileries Garden",
  "artist": "Guilhem Vellut from Tokyo, Japan",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Crowd_in_the_Jardin_des_Tuileries,_Paris_July_2014.jpg"
 },
 {
  "id": "vieux-port",
  "file": "La Ciotat - Chantiers navals.jpeg",
  "title": "La Ciotat chantiers navals portique",
  "artist": "Un Fou",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:La_Ciotat_-_Chantiers_navals.jpeg"
 },
 {
  "id": "vosges",
  "file": "Place_des_Vosges_vue_aérienne.png",
  "title": "Place des Vosges",
  "artist": "Des Racines et des Ailes",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Place_des_Vosges_vue_a%C3%A9rienne.png"
 },
 {
  "id": "whitehall",
  "file": "Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster,_London.jpg",
  "title": "Big Ben",
  "artist": "Christian David",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster,_London.jpg"
 }
];
